version: "3.8"

services:
  backend:
    image: fastapi-backend
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    image: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend